# Generated by Django 5.2.17 on 2026-09-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studygroup_user_study_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='issued_password',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
