# Generated by Django 5.2.17 on 2026-09-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_issued_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
