# Generated by Django 5.2.17 on 2026-09-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbookblock',
            name='card_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='workbookblock',
            name='card_style',
            field=models.CharField(blank=True, choices=[('', 'Звичайна'), ('profile', 'Про мене'), ('tool', 'Інструменти')], max_length=20),
        ),
        migrations.AddField(
            model_name='workbookblock',
            name='half_width',
            field=models.BooleanField(default=False),
        ),
    ]
